name: Windows build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: actions/checkout@v5
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        install: mingw-w64-x86_64-gcc
    - run: gcc --std=c11 -O2 -s -DPC_WIN32 -DUSE_C11_TIME_API -o inform6 *.c
    - uses: actions/upload-artifact@v4
      with:
        name: inform6_win
        path: inform6.exe
