name: Windows build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
    - shell: msys2 {0}
      run: clang -DPC_WIN32 -O2 -s -o inform6.exe *.c
